title: CedarML Compiler
description: >-
  Compiles CedarML into C code
baseurl: /cmlc
url: https://cailyn-baksh.github.io
keep_files: [javadoc]

#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
search_enabled: true
search:
  tokenizer_separator: /[\s\-_]+/
heading_anchors: true
aux_links:
  "View Source on GitHub":
    - "//github.com/cailyn-baksh/cmlc"

plugins:
  - jekyll-remote-theme

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "javadoc"
      type: "pages"
    values:
      nav_exclude: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
