title: CedarML Compiler
description: >-
  Compiles CedarML into C code
baseurl: /cmlc
url: https://cailyn-baksh.github.io

remote_theme: just-the-docs/just-the-docs
search_enabled: true
search:
  tokenizer_separator: /[\s\-_]+/
heading_anchors: true